"""
CoChem-TOPOS: Mechanics Subsystem
Provides hardware brokering, HDF5 SWMR state management, universal fallback cascade,
precision downgrade protocol, lightning PES quench relaxation, and topographic escape room
with Wigner-guided normal mode kicks and progressive Langevin thermal auto-tuning.
"""

from .cochem_topos_escape import (
    EscapeConfig,
    EscapeMechanism,
    EscapeResult,
    EscapeRoom,
    EscapeStatus,
    EscapeTelemetryPacket,
    FAIRProvenanceRecord,
    GoodTuringEstimator,
    IPCTelemetryBroadcaster,
    NormalModeAnalysisResult,
    ParityLock,
    PhotochemicalShockEngine,
    ProgressiveLangevinEscape,
    ToposEscapeOrchestrator,
    WignerGuidedEscape,
    WignerModeInfo,
    calculate_rmsd,
    canonical_geometry_hash,
    create_fair_provenance_record,
)
from .cochem_topos_memory import (
    CascadeState,
    DeviceType,
    EngineTier,
    FallbackCascadeStateMachine,
    FallbackReason,
    GeometryRecord,
    GPUDeviceInfo,
    HardwareResourceBroker,
    HardwareSnapshot,
    PrecisionDowngradeProtocol,
    PrecisionMode,
    TelemetryRecord,
    ToposHDF5MemoryManager,
    TrajectoryStep,
    UniversalFallbackCascade,
)
from .cochem_topos_quench import (
    CalculatorFactory,
    CUDAGraphOptimizerWrapper,
    ParallelASEQuenchRunner,
    QuenchAlgorithm,
    QuenchBatchResult,
    QuenchConfig,
    QuenchResult,
    QuenchStatus,
    SoftQuenchGovernor,
    SoftQuenchTelemetry,
    ToposQuenchOrchestrator,
    TorchMLFFCalculator,
)

__all__ = [
    # Memory and state management
    "ToposHDF5MemoryManager",
    "HardwareResourceBroker",
    "HardwareSnapshot",
    "GPUDeviceInfo",
    "UniversalFallbackCascade",
    "FallbackCascadeStateMachine",
    "EngineTier",
    "FallbackReason",
    "DeviceType",
    "PrecisionMode",
    "CascadeState",
    "PrecisionDowngradeProtocol",
    "GeometryRecord",
    "TrajectoryStep",
    "TelemetryRecord",
    # Quench and relaxation
    "CUDAGraphOptimizerWrapper",
    "CalculatorFactory",
    "ParallelASEQuenchRunner",
    "QuenchAlgorithm",
    "QuenchBatchResult",
    "QuenchConfig",
    "QuenchResult",
    "QuenchStatus",
    "SoftQuenchGovernor",
    "SoftQuenchTelemetry",
    "ToposQuenchOrchestrator",
    "TorchMLFFCalculator",
    # Escape room and basin exploration
    "EscapeConfig",
    "EscapeMechanism",
    "EscapeResult",
    "EscapeRoom",
    "EscapeStatus",
    "EscapeTelemetryPacket",
    "FAIRProvenanceRecord",
    "GoodTuringEstimator",
    "IPCTelemetryBroadcaster",
    "NormalModeAnalysisResult",
    "ParityLock",
    "PhotochemicalShockEngine",
    "ProgressiveLangevinEscape",
    "ToposEscapeOrchestrator",
    "WignerGuidedEscape",
    "WignerModeInfo",
    "calculate_rmsd",
    "canonical_geometry_hash",
    "create_fair_provenance_record",
]
