"""Regression against actual hosted ORCA timeout evidence, not native fixtures generated by tests."""
from __future__ import annotations

import json
from pathlib import Path

from topos.goat import parse_goat_progress
from topos.storage import file_digest

FIXTURE = Path(__file__).parent / "fixtures/goat_hosted_timeout"


def test_actual_hosted_timeout_records_workload_without_claiming_convergence():
    provenance = json.loads((FIXTURE / "provenance.json").read_text())
    assert file_digest(FIXTURE / "native-progress.stdout") == provenance["excerpt_sha256"]
    assert file_digest(FIXTURE / "native-process.json") == provenance["process_fixture_sha256"]
    process = json.loads((FIXTURE / "native-process.json").read_text())
    assert process["status"] == "timed-out" and process["returncode"] == -124
    assert 1190 < process["elapsed_seconds"] < 1205
    raw = (FIXTURE / "native-progress.stdout").read_text()
    progress = parse_goat_progress(raw)
    assert progress["minimum_global_iterations"] == 3
    assert progress["workers"] == 4 and progress["available_cpus"] == 2
    assert progress["optimizations_per_global_iteration"] == 60
    assert progress["optimizations_per_worker"] == 15
    assert progress["reported_global_iteration_indices"] == [1]
    assert progress["reported_global_iterations"] == 1
    assert not progress["finite_stopping_marker_present"]
    assert not progress["normal_termination_marker_present"]
    assert sum(worker["cartesian_gradient_count"] for worker in provenance["workers_first_global_iteration"]) == 1005
    assert sum(worker["scf_converged_count"] for worker in provenance["workers_first_global_iteration"]) == 1005


def test_global_heading_without_native_summary_row_does_not_count_as_completed_iteration():
    raw = (FIXTURE / "native-progress.stdout").read_text()
    partial = raw[:raw.index("GOAT Global Iter 1") + len("GOAT Global Iter 1")]
    progress = parse_goat_progress(partial)
    assert progress["reported_global_iterations"] == 0
    assert not progress["finite_stopping_marker_present"]


def test_empty_output_does_not_fabricate_native_workload_or_progress():
    progress = parse_goat_progress("")
    assert progress["workers"] is None
    assert progress["optimizations_per_global_iteration"] is None
    assert progress["reported_global_iteration_indices"] == []
    assert not progress["normal_termination_marker_present"]
