"""
CoChem-TOPOS: Escalation & Quantum Assembly Subsystem
Stage 3.0 & 4.0 Modules for Combinatorial Assembly and Ab Initio Escalation.
"""

from escalation.cochem_topos_assembly import (
    AssembledComplexCandidate,
    AssemblyConfig,
    AssemblySessionReport,
    BSSEFragmentConfig,
    CounterpoiseBSSEGenerator,
    DockingCollisionVector,
    FragmentSource,
    GeometricDockingEngine,
    InternalCoordinateConstraint,
    InternalCoordinateFreezer,
    StericClashReport,
    StericClashResolver,
    ToposCombinatorialAssembler,
    assemble_weak_complex,
)
from escalation.cochem_topos_escalator_exec import (
    AlertSeverity,
    AutoCASAlert,
    AutoCASRescueProtocol,
    AutomatedSCFRescueEngine,
    CalculationStatus,
    CoordinateType,
    CrossPlatformIPCAlert,
    CrossPlatformIPCClient,
    CrossPlatformIPCServer,
    EscalationResult,
    EscalationStepRecord,
    EscalationTier,
    EscalatorExecConfig,
    ExecutionPlan,
    FileSocketIPCQueue,
    GeometryCoordinateVerifier,
    MultireferenceDiagnostics,
    ORCAOutputParser,
    SCFConvergenceMetrics,
    SCFConvergenceStatus,
    SCFIterationRecord,
    TimeAwareCapabilitySelector,
    ToposEscalatorExec,
    execute_time_aware_escalation,
    parse_orca_output,
    send_ipc_alert,
    verify_redundant_cartesian_geometry,
)

from escalation.cochem_topos_iso_recycle import (
    HESSIAN_UNIT_FACTORS,
    HarmonicKIE,
    HessianUnit,
    IsotopeSubstitution,
    IsotopologueDefinition,
    IsotopologueRecycleResult,
    NormalMode,
    ThermochemicalCorrections,
    ToposIsotopologueRecycler,
    VibrationalAnalysis,
    calculate_harmonic_kie,
    get_exact_isotopic_mass,
    get_isotopic_masses,
    mass_weight_hessian,
    project_translations_rotations,
    recycle_hessian_frequencies,
)

__all__ = [
    # Stage 3.0 Assembly exports
    "FragmentSource",
    "DockingCollisionVector",
    "StericClashReport",
    "InternalCoordinateConstraint",
    "BSSEFragmentConfig",
    "AssembledComplexCandidate",
    "AssemblyConfig",
    "AssemblySessionReport",
    "StericClashResolver",
    "CounterpoiseBSSEGenerator",
    "InternalCoordinateFreezer",
    "GeometricDockingEngine",
    "ToposCombinatorialAssembler",
    "assemble_weak_complex",
    # Stage 4.0 Escalator Execution exports
    "EscalationTier",
    "SCFConvergenceStatus",
    "CalculationStatus",
    "AlertSeverity",
    "CoordinateType",
    "MultireferenceDiagnostics",
    "SCFIterationRecord",
    "SCFConvergenceMetrics",
    "AutoCASAlert",
    "CrossPlatformIPCAlert",
    "ExecutionPlan",
    "EscalationStepRecord",
    "EscalatorExecConfig",
    "EscalationResult",
    "GeometryCoordinateVerifier",
    "ORCAOutputParser",
    "AutomatedSCFRescueEngine",
    "AutoCASRescueProtocol",
    "FileSocketIPCQueue",
    "CrossPlatformIPCServer",
    "CrossPlatformIPCClient",
    "TimeAwareCapabilitySelector",
    "ToposEscalatorExec",
    "execute_time_aware_escalation",
    "verify_redundant_cartesian_geometry",
    "parse_orca_output",
    "send_ipc_alert",
    # Stage 4.1 Isotopologue Hessian Recycling exports
    "HessianUnit",
    "HESSIAN_UNIT_FACTORS",
    "IsotopeSubstitution",
    "IsotopologueDefinition",
    "NormalMode",
    "ThermochemicalCorrections",
    "VibrationalAnalysis",
    "IsotopologueRecycleResult",
    "HarmonicKIE",
    "ToposIsotopologueRecycler",
    "get_exact_isotopic_mass",
    "get_isotopic_masses",
    "mass_weight_hessian",
    "project_translations_rotations",
    "recycle_hessian_frequencies",
    "calculate_harmonic_kie",
]

